version: 2
updates:
  - package-ecosystem: "terraform"
    directory: "/"
    schedule:
      interval: "daily"
    groups:
      Providers-version-updates:
        patterns:
          - "*"
    
    commit-message:
      prefix: "deps"
      include: "scope"

    open-pull-requests-limit: 10



#Current config
# version: 2
# updates:
#   # Enable version updates for npm
#   - package-ecosystem: "terraform"
#     # Look for `package.json` and `lock` files in the `root` directory
#     directory: "version3/"
#     # Check the npm registry for updates every day (weekdays)
#     schedule:
#       interval: "daily"


